<?php

declare(strict_types=1);

namespace Yard\Gutenberg;

use Yard\Gutenberg\Support\AllowedBlocks;

class PluginServiceProvider
{
	public function boot()
	{
		$this->bootProviders();

		\add_filter('block_categories_all', [$this, 'addBlockCategory']);
		\add_action('init', [$this, 'registerBlocks']);

		\add_action('enqueue_block_editor_assets', function () {
			wp_register_script('yard-facetwp', null);

			wp_localize_script('yard-facetwp', 'facetWP', [
				// Remove "pager" facets as they are not used as facets.
				'facets' => function_exists('FWP') ? array_values(array_filter(\FWP()->helper->get_facets(), fn ($f) => 'pager' !== ($f['type'] ?? ''))) : [],
				'templates' => function_exists('FWP') ? \FWP()->helper->get_templates() : [],
			]);

			wp_enqueue_script('yard-facetwp');
		});
	}

	/**
	 * Boot all providers
	 */
	public function bootProviders(): void
	{
		$providers = [
			Hooks\DefaultHookManager::class,
			MyPatterns\MyPatternManager::class,
			Patterns\PatternManager::class,
			PhpBlocks\PhpBlockManager::class,
			YardPatterns\YardPatternsManager::class,
		];

		foreach ($providers as $provider) {
			$provider = new $provider();
			$provider->boot();
		}
	}

	/**
	 * Add a custom block category
	 */
	public function addBlockCategory(array $categories)
	{
		if (in_array('yard', array_column($categories, 'slug'))) {
			return $categories;
		}

		$categories = array_merge($categories, [
			[
				'slug' => 'yard',
				'title' => 'Yard',
			],
		]);

		return $categories;
	}

	/**
	 * Registers the block using the metadata loaded from the `block.json` file.
	 * Behind the scenes, it registers also all assets so they can be enqueued
	 * through the block editor in the corresponding context.
	 *
	 * If a blocks-manifest.php is available (generated by wp-scripts'
	 * `--blocks-manifest` flag as part of `npm run build`), its metadata
	 * collection is registered first so `register_block_type()` reads every
	 * block's data from that one already-loaded array instead of reading
	 * and JSON-decoding each block.json from disk on every request. Older
	 * builds without a manifest fall back to reading block.json from disk.
	 *
	 * @see https://developer.wordpress.org/reference/functions/register_block_type/
	 * @see https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#blocks-manifest
	 */
	public function registerBlocks()
	{
		$blocksPath = dirname(__DIR__, 1) . '/build/Blocks/';
		$manifestPath = dirname($blocksPath) . '/blocks-manifest.php';

		if (function_exists('wp_register_block_metadata_collection') && file_exists($manifestPath)) {
			wp_register_block_metadata_collection($blocksPath, $manifestPath);
		}

		$blockNames = array_map('basename', array_filter(glob($blocksPath . '*', GLOB_ONLYDIR) ?: []));

		// Skip leftover directories from an earlier build that no longer hold a block.
		$blockNames = array_filter($blockNames, function (string $blockName) use ($blocksPath) {
			return file_exists($blocksPath . $blockName . '/block.json');
		});

		$blockNames = AllowedBlocks::filter($blockNames);

		foreach ($blockNames as $blockName) {
			$blockPath = $blocksPath . $blockName;
			$renderCallback = $this->getRenderCallback($blockName);

			\register_block_type($blockPath, $renderCallback ? ['render_callback' => $renderCallback] : []);
		}
	}

	/**
	 * Get the render callback for a dynamic block, if a matching render class exists.
	 *
	 * Block names containing a hyphen (e.g. `collapse-item`) can never map to a
	 * valid PHP class name under our namespacing convention, so they're skipped
	 * before the `class_exists()` autoload lookup.
	 *
	 * @param string $blockName The name of the block.
	 *
	 * @return callable|null The render callback or null if the block isn't dynamic.
	 */
	public function getRenderCallback(string $blockName): ?callable
	{
		if (false !== strpos($blockName, '-')) {
			return null;
		}
		$nameSpacedClass = 'Yard\\Gutenberg\\Blocks\\' . $blockName . '\\' . ucfirst($blockName);

		if (class_exists($nameSpacedClass)) {
			$blockClass = new $nameSpacedClass;

			return [$blockClass, 'renderCallback'];
		}

		return null;
	}
}
